/* Generated by Frama-C */
char *__gen_e_acsl_literal_string_3;
char *__gen_e_acsl_literal_string;
char *__gen_e_acsl_literal_string_2;
char *S = (char *)"foo";
int f(void)
{
  int __retres;
  char *s1;
  char *s2;
  __e_acsl_store_block((void *)(& s2),8UL);
  __e_acsl_store_block((void *)(& s1),8UL);
  __e_acsl_full_init((void *)(& s1));
  s1 = (char *)__gen_e_acsl_literal_string;
  __e_acsl_full_init((void *)(& s2));
  s2 = (char *)__gen_e_acsl_literal_string_2;
  /*@ assert \valid_read(S); */
  {
    int __gen_e_acsl_valid_read;
    __gen_e_acsl_valid_read = __e_acsl_valid_read((void *)S,sizeof(char));
    __e_acsl_assert(__gen_e_acsl_valid_read,(char *)"Assertion",(char *)"f",
                    (char *)"\\valid_read(S)",10);
  }
  /*@ assert \valid_read(s1); */
  {
    int __gen_e_acsl_initialized;
    int __gen_e_acsl_and;
    __gen_e_acsl_initialized = __e_acsl_initialized((void *)(& s1),
                                                    sizeof(char *));
    if (__gen_e_acsl_initialized) {
      int __gen_e_acsl_valid_read_2;
      __gen_e_acsl_valid_read_2 = __e_acsl_valid_read((void *)s1,
                                                      sizeof(char));
      __gen_e_acsl_and = __gen_e_acsl_valid_read_2;
    }
    else __gen_e_acsl_and = 0;
    __e_acsl_assert(__gen_e_acsl_and,(char *)"Assertion",(char *)"f",
                    (char *)"\\valid_read(s1)",11);
  }
  /*@ assert \valid_read(s2); */
  {
    int __gen_e_acsl_initialized_2;
    int __gen_e_acsl_and_2;
    __gen_e_acsl_initialized_2 = __e_acsl_initialized((void *)(& s2),
                                                      sizeof(char *));
    if (__gen_e_acsl_initialized_2) {
      int __gen_e_acsl_valid_read_3;
      __gen_e_acsl_valid_read_3 = __e_acsl_valid_read((void *)s2,
                                                      sizeof(char));
      __gen_e_acsl_and_2 = __gen_e_acsl_valid_read_3;
    }
    else __gen_e_acsl_and_2 = 0;
    __e_acsl_assert(__gen_e_acsl_and_2,(char *)"Assertion",(char *)"f",
                    (char *)"\\valid_read(s2)",12);
  }
  __retres = 0;
  __e_acsl_delete_block((void *)(& s2));
  __e_acsl_delete_block((void *)(& s1));
  return __retres;
}

void __e_acsl_globals_init(void)
{
  __gen_e_acsl_literal_string_3 = "toto";
  __e_acsl_store_block((void *)__gen_e_acsl_literal_string_3,sizeof("toto"));
  __e_acsl_full_init((void *)__gen_e_acsl_literal_string_3);
  __e_acsl_readonly((void *)__gen_e_acsl_literal_string_3);
  __gen_e_acsl_literal_string = "foo";
  __e_acsl_store_block((void *)__gen_e_acsl_literal_string,sizeof("foo"));
  __e_acsl_full_init((void *)__gen_e_acsl_literal_string);
  __e_acsl_readonly((void *)__gen_e_acsl_literal_string);
  __gen_e_acsl_literal_string_2 = "bar";
  __e_acsl_store_block((void *)__gen_e_acsl_literal_string_2,sizeof("bar"));
  __e_acsl_full_init((void *)__gen_e_acsl_literal_string_2);
  __e_acsl_readonly((void *)__gen_e_acsl_literal_string_2);
  __e_acsl_store_block((void *)(& S),8UL);
  __e_acsl_full_init((void *)(& S));
  return;
}

int main(void)
{
  int __retres;
  int i;
  __e_acsl_memory_init((int *)0,(char ***)0,8UL);
  __e_acsl_globals_init();
  i = 4;
  while (1) {
    int tmp;
    { /* sequence */
      tmp = i;
      /*@ assert Value: signed_overflow: -2147483648 ≤ i - 1; */
      i --;
      ;
    }
    if (! tmp) break;
    {
      char *s;
      __e_acsl_store_block((void *)(& s),8UL);
      __e_acsl_full_init((void *)(& s));
      s = (char *)__gen_e_acsl_literal_string_3;
      /*@ assert \valid_read(s); */
      {
        int __gen_e_acsl_initialized;
        int __gen_e_acsl_and;
        __gen_e_acsl_initialized = __e_acsl_initialized((void *)(& s),
                                                        sizeof(char *));
        if (__gen_e_acsl_initialized) {
          int __gen_e_acsl_valid_read;
          __gen_e_acsl_valid_read = __e_acsl_valid_read((void *)s,
                                                        sizeof(char));
          __gen_e_acsl_and = __gen_e_acsl_valid_read;
        }
        else __gen_e_acsl_and = 0;
        __e_acsl_assert(__gen_e_acsl_and,(char *)"Assertion",(char *)"main",
                        (char *)"\\valid_read(s)",20);
      }
      /*@ assert ¬\valid(s); */
      {
        int __gen_e_acsl_initialized_2;
        int __gen_e_acsl_and_2;
        __gen_e_acsl_initialized_2 = __e_acsl_initialized((void *)(& s),
                                                          sizeof(char *));
        if (__gen_e_acsl_initialized_2) {
          int __gen_e_acsl_valid;
          __gen_e_acsl_valid = __e_acsl_valid((void *)s,sizeof(char));
          __gen_e_acsl_and_2 = __gen_e_acsl_valid;
        }
        else __gen_e_acsl_and_2 = 0;
        __e_acsl_assert(! __gen_e_acsl_and_2,(char *)"Assertion",
                        (char *)"main",(char *)"!\\valid(s)",21);
        __e_acsl_delete_block((void *)(& s));
      }
    }
  }
  f();
  __retres = 0;
  __e_acsl_delete_block((void *)(& S));
  __e_acsl_memory_clean();
  return __retres;
}


