/* Generated by Frama-C */
int *p;
void __e_acsl_globals_init(void)
{
  __e_acsl_store_block((void *)(& p),8UL);
  __e_acsl_full_init((void *)(& p));
  return;
}

int main(void)
{
  int __retres;
  int i;
  int t[10];
  __e_acsl_memory_init((int *)0,(char ***)0,8UL);
  __e_acsl_globals_init();
  __e_acsl_store_block((void *)(t),40UL);
  i = -1;
  /*@ assert ¬\valid_read(&t[i]); */
  {
    int __gen_e_acsl_valid_read;
    __gen_e_acsl_valid_read = __e_acsl_valid_read((void *)(& t[i]),
                                                  sizeof(int));
    __e_acsl_assert(! __gen_e_acsl_valid_read,(char *)"Assertion",
                    (char *)"main",(char *)"!\\valid_read(&t[i])",9);
  }
  p = t;
  /*@ assert ¬\valid_read(p + i); */
  {
    int __gen_e_acsl_valid_read_2;
    __gen_e_acsl_valid_read_2 = __e_acsl_valid_read((void *)(p + i),
                                                    sizeof(int));
    __e_acsl_assert(! __gen_e_acsl_valid_read_2,(char *)"Assertion",
                    (char *)"main",(char *)"!\\valid_read(p + i)",11);
  }
  __retres = 0;
  __e_acsl_delete_block((void *)(& p));
  __e_acsl_delete_block((void *)(t));
  __e_acsl_memory_clean();
  return __retres;
}


