/* Generated by Frama-C */
int global_i;

int *global_i_ptr = & global_i;
int global_i = 0;
/*@ requires global_i ≡ 0;
    requires \valid(global_i_ptr);
    requires global_i_ptr ≡ &global_i;
 */
void __gen_e_acsl_loop(void);

/*@ requires global_i ≡ 0;
    requires \valid(global_i_ptr);
    requires global_i_ptr ≡ &global_i;
 */
void loop(void)
{
  return;
}

/*@ requires global_i ≡ 0;
    requires \valid(global_i_ptr);
    requires global_i_ptr ≡ &global_i;
 */
void __gen_e_acsl_loop(void)
{
  {
    int __gen_e_acsl_valid;
    __e_acsl_assert(global_i == 0,(char *)"Precondition",(char *)"loop",
                    (char *)"global_i == 0",9);
    __gen_e_acsl_valid = __e_acsl_valid((void *)global_i_ptr,sizeof(int));
    __e_acsl_assert(__gen_e_acsl_valid,(char *)"Precondition",(char *)"loop",
                    (char *)"\\valid(global_i_ptr)",10);
    __e_acsl_assert(global_i_ptr == & global_i,(char *)"Precondition",
                    (char *)"loop",(char *)"global_i_ptr == &global_i",11);
    loop();
  }
  return;
}

void __e_acsl_globals_init(void)
{
  __e_acsl_store_block((void *)(& global_i_ptr),8UL);
  __e_acsl_full_init((void *)(& global_i_ptr));
  __e_acsl_store_block((void *)(& global_i),4UL);
  __e_acsl_full_init((void *)(& global_i));
  return;
}

int main(void)
{
  int __retres;
  __e_acsl_memory_init((int *)0,(char ***)0,8UL);
  __e_acsl_globals_init();
  __gen_e_acsl_loop();
  __retres = 0;
  __e_acsl_delete_block((void *)(& global_i_ptr));
  __e_acsl_delete_block((void *)(& global_i));
  __e_acsl_memory_clean();
  return __retres;
}


