/* Generated by Frama-C */
void f(void)
{
  int m;
  int *u;
  int *p;
  __e_acsl_store_block((void *)(& p),8UL);
  __e_acsl_store_block((void *)(& u),8UL);
  __e_acsl_store_block((void *)(& m),4UL);
  __e_acsl_full_init((void *)(& u));
  u = & m;
  __e_acsl_full_init((void *)(& p));
  p = u;
  __e_acsl_full_init((void *)(& m));
  m = 123;
  /*@ assert \initialized(p); */
  {
    int __gen_e_acsl_initialized;
    __gen_e_acsl_initialized = __e_acsl_initialized((void *)p,sizeof(int));
    __e_acsl_assert(__gen_e_acsl_initialized,(char *)"Assertion",(char *)"f",
                    (char *)"\\initialized(p)",10);
  }
  __e_acsl_delete_block((void *)(& p));
  __e_acsl_delete_block((void *)(& u));
  __e_acsl_delete_block((void *)(& m));
  return;
}

void __e_acsl_globals_init(void)
{
  __e_acsl_store_block((void *)(& __fc_rand_max),8UL);
  __e_acsl_full_init((void *)(& __fc_rand_max));
  __e_acsl_store_block((void *)(& __fc_random_counter),4UL);
  __e_acsl_full_init((void *)(& __fc_random_counter));
  return;
}

int main(void)
{
  int __retres;
  int x;
  __e_acsl_memory_init((int *)0,(char ***)0,8UL);
  __e_acsl_globals_init();
  __e_acsl_store_block((void *)(& x),4UL);
  __e_acsl_store_block((void *)(& __retres),4UL);
  __e_acsl_full_init((void *)(& x));
  x = 0;
  f();
  /*@ assert &x ≡ &x; */
  __e_acsl_assert(& x == & x,(char *)"Assertion",(char *)"main",
                  (char *)"&x == &x",16);
  __e_acsl_full_init((void *)(& __retres));
  __retres = 0;
  __e_acsl_delete_block((void *)(& __fc_rand_max));
  __e_acsl_delete_block((void *)(& __fc_random_counter));
  __e_acsl_delete_block((void *)(& x));
  __e_acsl_delete_block((void *)(& __retres));
  __e_acsl_memory_clean();
  return __retres;
}


