/* Generated by Frama-C */
enum bool {
    false = 0,
    true = 1
};
int main(void)
{
  int __retres;
  /*@ assert 'c' ≡ 'c'; */
  __e_acsl_assert('c' == 'c',(char *)"Assertion",(char *)"main",
                  (char *)"\'c\' == \'c\'",10);
  /*@ assert false ≢ true; */
  __e_acsl_assert(false != true,(char *)"Assertion",(char *)"main",
                  (char *)"false != true",11);
  __retres = 0;
  return __retres;
}


