/* Generated by Frama-C */
int main(void)
{
  int __retres;
  int x;
  x = 0;
  x ++;
  /*@ assert \true; */
  __e_acsl_assert(1,(char *)"Assertion",(char *)"main",(char *)"\\true",8);
  __retres = 0;
  return __retres;
}


