/* Generated by Frama-C */
int main(void)
{
  int __retres;
  int x;
  int y;
  x = 0;
  y = 2;
  /*@ ensures x ≡ 1; */
  {
    x = 1;
    __e_acsl_assert(x == 1,(char *)"Postcondition",(char *)"main",
                    (char *)"x == 1",8);
  }
  /*@ ensures x ≡ 2;
      ensures y ≡ 2; */
  {
    x = 2;
    __e_acsl_assert(x == 2,(char *)"Postcondition",(char *)"main",
                    (char *)"x == 2",11);
    __e_acsl_assert(y == 2,(char *)"Postcondition",(char *)"main",
                    (char *)"y == 2",12);
  }
  /*@ requires x ≡ 2; */
  __e_acsl_assert(x == 2,(char *)"Precondition",(char *)"main",
                  (char *)"x == 2",15);
  x ++;
  /*@ requires x ≡ 3;
      requires y ≡ 2; */
  __e_acsl_assert(x == 3,(char *)"Precondition",(char *)"main",
                  (char *)"x == 3",18);
  __e_acsl_assert(y == 2,(char *)"Precondition",(char *)"main",
                  (char *)"y == 2",19);
  x += y;
  /*@ behavior b1:
        requires x ≡ 5;
        ensures x ≡ 3;
      
      behavior b2:
        requires x ≡ 3 + y;
        requires y ≡ 2;
        ensures x ≡ y + 1;
  */
  {
    __e_acsl_assert(x == 5,(char *)"Precondition",(char *)"main",
                    (char *)"x == 5",23);
    __e_acsl_assert(x == 3L + y,(char *)"Precondition",(char *)"main",
                    (char *)"x == 3 + y",26);
    __e_acsl_assert(y == 2,(char *)"Precondition",(char *)"main",
                    (char *)"y == 2",27);
    x = 3;
    __e_acsl_assert(x == 3,(char *)"Postcondition",(char *)"main",
                    (char *)"x == 3",24);
    __e_acsl_assert(x == y + 1L,(char *)"Postcondition",(char *)"main",
                    (char *)"x == y + 1",28);
  }
  /*@ behavior b1:
        assumes x ≡ 1;
        requires x ≡ 0;
      
      behavior b2:
        assumes x ≡ 3;
        assumes y ≡ 2;
        requires x ≡ 3;
        requires x + y ≡ 5;
  */
  {
    int __gen_e_acsl_implies;
    int __gen_e_acsl_and;
    int __gen_e_acsl_implies_2;
    int __gen_e_acsl_and_2;
    int __gen_e_acsl_implies_3;
    if (! (x == 1)) __gen_e_acsl_implies = 1;
    else __gen_e_acsl_implies = x == 0;
    __e_acsl_assert(__gen_e_acsl_implies,(char *)"Precondition",
                    (char *)"main",(char *)"x == 1 ==> x == 0",33);
    if (x == 3) __gen_e_acsl_and = y == 2; else __gen_e_acsl_and = 0;
    if (! __gen_e_acsl_and) __gen_e_acsl_implies_2 = 1;
    else __gen_e_acsl_implies_2 = x == 3;
    __e_acsl_assert(__gen_e_acsl_implies_2,(char *)"Precondition",
                    (char *)"main",(char *)"x == 3 && y == 2 ==> x == 3",37);
    if (x == 3) __gen_e_acsl_and_2 = y == 2; else __gen_e_acsl_and_2 = 0;
    if (! __gen_e_acsl_and_2) __gen_e_acsl_implies_3 = 1;
    else __gen_e_acsl_implies_3 = x + y == 5L;
    __e_acsl_assert(__gen_e_acsl_implies_3,(char *)"Precondition",
                    (char *)"main",(char *)"x == 3 && y == 2 ==> x + y == 5",
                    38);
    x += y;
  }
  /*@ requires x ≡ 5; */
  __e_acsl_assert(x == 5,(char *)"Precondition",(char *)"main",
                  (char *)"x == 5",41);
  /*@ requires y ≡ 2; */
  __e_acsl_assert(y == 2,(char *)"Precondition",(char *)"main",
                  (char *)"y == 2",42);
  x += y;
  /*@ requires x ≡ 7;
      ensures x ≡ 7; */
  {
    __e_acsl_assert(x == 7,(char *)"Precondition",(char *)"main",
                    (char *)"x == 7",45);
    __retres = 0;
    __e_acsl_assert(x == 7,(char *)"Postcondition",(char *)"main",
                    (char *)"x == 7",46);
  }
  return __retres;
}


