/* Generated by Frama-C */
int main(int argc, char const **argv)
{
  int __retres;
  char c;
  int tmp;
  char *d;
  __e_acsl_memory_init(& argc,(char ***)(& argv),8UL);
  __e_acsl_store_block((void *)(& d),8UL);
  __e_acsl_store_block((void *)(& c),1UL);
  tmp = __gen_e_acsl_isupper(argc);
  __e_acsl_full_init((void *)(& c));
  c = (char)tmp;
  __e_acsl_full_init((void *)(& d));
  d = & c;
  /*@ assert \valid(d); */
  {
    int __gen_e_acsl_initialized;
    int __gen_e_acsl_and;
    __gen_e_acsl_initialized = __e_acsl_initialized((void *)(& d),
                                                    sizeof(char *));
    if (__gen_e_acsl_initialized) {
      int __gen_e_acsl_valid;
      __gen_e_acsl_valid = __e_acsl_valid((void *)d,sizeof(char));
      __gen_e_acsl_and = __gen_e_acsl_valid;
    }
    else __gen_e_acsl_and = 0;
    __e_acsl_assert(__gen_e_acsl_and,(char *)"Assertion",(char *)"main",
                    (char *)"\\valid(d)",39);
  }
  __retres = 0;
  __e_acsl_delete_block((void *)(& d));
  __e_acsl_delete_block((void *)(& c));
  __e_acsl_memory_clean();
  return __retres;
}


