/* Generated by Frama-C */
int main(void)
{
  int __retres;
  int x;
  x = 0;
  if (x) 
    /*@ assert \false; */
    __e_acsl_assert(0,(char *)"Assertion",(char *)"main",(char *)"\\false",6);
  __retres = 0;
  return __retres;
}


