/* Generated by Frama-C */
int main(void)
{
  int __retres;
  char *a;
  __e_acsl_memory_init((int *)0,(char ***)0,8UL);
  a = (char *)malloc((unsigned long)7);
  __retres = 0;
  __e_acsl_memory_clean();
  return __retres;
}


