/* Generated by Frama-C */
int main(void)
{
  int __retres;
  int x;
  x = 0;
  x ++;
  /*@ assert sizeof(int) ≡ sizeof(x); */
  __e_acsl_assert(4 == 4,(char *)"Assertion",(char *)"main",
                  (char *)"sizeof(int) == sizeof(x)",8);
  __retres = 0;
  return __retres;
}


