/* Generated by Frama-C */
void f(int *dest, int val)
{
  int *ptr;
  __e_acsl_store_block((void *)(& ptr),8UL);
  __e_acsl_store_block((void *)(& dest),8UL);
  __e_acsl_full_init((void *)(& ptr));
  ptr = dest;
  __e_acsl_initialize((void *)ptr,sizeof(int));
  *ptr = val;
  __e_acsl_delete_block((void *)(& dest));
  __e_acsl_delete_block((void *)(& ptr));
  return;
}

int main(void)
{
  int __retres;
  int i;
  __e_acsl_memory_init((int *)0,(char ***)0,8UL);
  __e_acsl_store_block((void *)(& i),4UL);
  f(& i,255);
  /*@ assert \initialized(&i); */
  {
    int __gen_e_acsl_initialized;
    __gen_e_acsl_initialized = __e_acsl_initialized((void *)(& i),
                                                    sizeof(int));
    __e_acsl_assert(__gen_e_acsl_initialized,(char *)"Assertion",
                    (char *)"main",(char *)"\\initialized(&i)",14);
  }
  __retres = 0;
  __e_acsl_delete_block((void *)(& i));
  __e_acsl_memory_clean();
  return __retres;
}


