/* Generated by Frama-C */
int main(void)
{
  int __retres;
  int x;
  x = 0;
  /*@ assert x ≡ 0; */
  __e_acsl_assert(x == 0,(char *)"Assertion",(char *)"main",(char *)"x == 0",
                  6);
  if (x) 
    /*@ assert x ≢ 0; */
    __e_acsl_assert(x != 0,(char *)"Assertion",(char *)"main",
                    (char *)"x != 0",7);
  __retres = 0;
  return __retres;
}


